### ISSUE TITLE
Add links to homepage

### ISSUE THREAD

**Issue by danalexilewis** [enspiral-root-systems/meta#30]
Add links to other pods:

- golden pandas
- protozoa
- opti.mii

Add link to our venture buddies
- Enspiral Venture page

Links to networks
- Enspiral

**Comment by ahdinosaur** [comment]
if we want to expand on this even more, we can create a new page "Ecosystem" in "Context" where we list all these groups and our relationships with them.

**Comment by bhaugen** [comment]
Holodex?

**Comment by danalexilewis** [comment]
@bhaugen yeah that's exactly what it is. But for now just a list ;)
