### ISSUE TITLE
Agreement: Decision making

### ISSUE THREAD

**Issue by danalexilewis** [enspiral-root-systems/meta#54]
This came up for me recently - we need a simple agreement about what a full consensus agreement is. 

I think we can keep it pretty straight forward - its either full agreement (all thumbs up) or majority agreement with no blocks.

Thoughts?
@sarah-arrrgh @ahdinosaur @gregorykan @iainkirkpatrick

**Comment by danalexilewis** [comment]
I thought we could reference the one in Enspiral - but thought it was to heavy for what we needed.
https://handbook.enspiral.com/decisions_agreement.html

**Comment by ahdinosaur** [comment]
:+1: re-use the Enspiral decision agreement, i'm not sure if it's too heavy.

**Comment by ahdinosaur** [comment]
merged in Enspiral decisions agreement here: https://github.com/enspiral-root-systems/meta/pull/84.

feedback welcome. my opinion is that the Enspiral decisions agreement makes sense for us, even if we haven't yet hit any of the edge cases that lead to the additional complexity in the Enspiral agreement.
