### ISSUE TITLE
Enspiral RS or no?

### ISSUE THREAD

**Issue by ahdinosaur** [enspiral-root-systems/meta#89]
at the moment the home page says "Enspiral Root Systems", but we haven't asked for permission to use the Enspiral brand since the [brand agreement](https://handbook.enspiral.com/brand_agreement.html).

we should either

- get permission to use the Enspiral brand
- only refer to ourselves as Root Systems

or both, so the default is Root Systems but we have permission to invoke the Enspiral brand as makes sense.

for context, i'm the one who made the initial name Enspiral Root Systems, since i wanted to provide credit and show connection to our parent network. i still use this name when identifying outside of the Enspiral network.

**Comment by danalexilewis** [comment]
I'm pretty easy on this. Enspiral root systems or Root systems of the enspiral network
